### ISSUE TITLE
failed to load package: core

### ISSUE THREAD

**Issue by evrim** [spicecrm/spicecrm#10]
Hi there,

I've tried to install master and rel 202401001 yet failed. The core package somehow does not install hence the crm is mostly unusable. Its on deb 12.6/12.7 with php8.2 mariadb elastic 8.x.

any ideas?
best,
evrim.

```
{
    "error": {
        "message": "Failed to load packages core",
        "errorCode": "packageLoadFailed",
        "details": [
            {
                "scope": "dictionary",
                "name": "Shop",
                "mismatch": null,
                "message": "DomainDefinition for id 3035d8dc-4d9e-9160-6a00-4eca67d06ba6 no found"
            },
            {
                "scope": "dictionary",
                "name": "SpiceImport",
                "mismatch": null,
                "message": "DomainDefinition for id 3035d8dc-4d9e-9160-6a00-4eca67d06ba6 no found"
            },
            {
                "scope": "dictionary",
                "name": "SpiceImportTemplate",
                "mismatch": null,
                "message": "DomainDefinition for id 3035d8dc-4d9e-9160-6a00-4eca67d06ba6 no found"
            },
            {
                "scope": "dictionary",
                "name": "SpiceText",
                "mismatch": null,
                "message": "DomainDefinition for id 3035d8dc-4d9e-9160-6a00-4eca67d06ba6 no found"
            },
            {
                "scope": "dictionary",
                "name": "AccountBankAccount",
                "mismatch": null,
                "message": "DomainDefinition for id 3035d8dc-4d9e-9160-6a00-4eca67d06ba6 no found"
            },
            {
                "scope": "dictionary",
                "name": "SchedulerJobTask",
                "mismatch": null,
                "message": "DomainDefinition for id 3035d8dc-4d9e-9160-6a00-4eca67d06ba6 no found"
            },
            {
                "scope": "dictionary",
                "name": "AccountCCDetail",
                "mismatch": null,
                "message": "DomainDefinition for id 3035d8dc-4d9e-9160-6a00-4eca67d06ba6 no found"
            },
            {
                "scope": "dictionary",
                "name": "AccountKPI",
                "mismatch": null,
                "message": "DomainDefinition for id 3035d8dc-4d9e-9160-6a00-4eca67d06ba6 no found"
            },
            {
                "scope": "dictionary",
                "name": "Account",
                "mismatch": null,
                "message": "DomainDefinition for id 3035d8dc-4d9e-9160-6a00-4eca67d06ba6 no found"
            },
            {
                "scope": "dictionary",
                "name": "Task",
                "mismatch": null,
                "message": "DomainDefinition for id 3035d8dc-4d9e-9160-6a00-4eca67d06ba6 no found"
            },
            {
                "scope": "dictionary",
                "name": "SystemHolidayCalendarDay",
                "mismatch": null,
                "message": "DomainDefinition for id 3035d8dc-4d9e-9160-6a00-4eca67d06ba6 no found"
            },
            {
                "scope": "dictionary",
                "name": "SystemHolidayCalendar",
                "mismatch": null,
                "message": "DomainDefinition for id 3035d8dc-4d9e-9160-6a00-4eca67d06ba6 no found"
            },
            {
                "scope": "dictionary",
                "name": "AccountVATID",
                "mismatch": null,
                "message": "DomainDefinition for id 3035d8dc-4d9e-9160-6a00-4eca67d06ba6 no found"
            },
            {
                "scope": "dictionary",
                "name": "Address",
                "mismatch": null,
                "message": "DomainDefinition for id 3035d8dc-4d9e-9160-6a00-4eca67d06ba6 no found"
            },
            {
                "scope": "dictionary",
                "name": "UserAbsence",
                "mismatch": null,
                "message": "DomainDefinition for id 3035d8dc-4d9e-9160-6a00-4eca67d06ba6 no found"
            },
            {
                "scope": "dictionary",
                "name": "Agreement",
                "mismatch": null,
                "message": "DomainDefinition for id 3035d8dc-4d9e-9160-6a00-4eca67d06ba6 no found"
            },
            {
                "scope": "dictionary",
                "name": "CallAttempt",
                "mismatch": null,
                "message": "DomainDefinition for id 3035d8dc-4d9e-9160-6a00-4eca67d06ba6 no found"
            },
            {
                "scope": "dictionary",
                "name": "spiceurls",
                "mismatch": null,
                "message": "DomainDefinition for id 3035d8dc-4d9e-9160-6a00-4eca67d06ba6 no found"
            },
            {
                "scope": "dictionary",
                "name": "UserQuota",
                "mismatch": null,
                "message": "DomainDefinition for id 3035d8dc-4d9e-9160-6a00-4eca67d06ba6 no found"
            },
            {
                "scope": "dictionary",
                "name": "Call",
                "mismatch": null,
                "message": "DomainDefinition for id 3035d8dc-4d9e-9160-6a00-4eca67d06ba6 no found"
            },
            {
                "scope": "dictionary",
                "name": "ContactCCDetail",
                "mismatch": null,
                "message": "DomainDefinition for id 3035d8dc-4d9e-9160-6a00-4eca67d06ba6 no found"
            },
            {
                "scope": "dictionary",
                "name": "ContactsOnlineProfile",
                "mismatch": null,
                "message": "DomainDefinition for id 3035d8dc-4d9e-9160-6a00-4eca67d06ba6 no found"
            },
            {
                "scope": "dictionary",
                "name": "DashboardSet",
                "mismatch": null,
                "message": "DomainDefinition for id 3035d8dc-4d9e-9160-6a00-4eca67d06ba6 no found"
            },
            {
                "scope": "dictionary",
                "name": "CompanyCode",
                "mismatch": null,
                "message": "DomainDefinition for id 3035d8dc-4d9e-9160-6a00-4eca67d06ba6 no found"
            },
            {
                "scope": "dictionary",
                "name": "CompanyFiscalPeriod",
                "mismatch": null,
                "message": "DomainDefinition for id 3035d8dc-4d9e-9160-6a00-4eca67d06ba6 no found"
            },
            {
                "scope": "dictionary",
                "name": "Contact",
                "mismatch": null,
                "message": "DomainDefinition for id 3035d8dc-4d9e-9160-6a00-4eca67d06ba6 no found"
            },
            {
                "scope": "dictionary",
                "name": "accounts_contacts",
                "mismatch": null,
                "message": "DomainDefinition for id 3035d8dc-4d9e-9160-6a00-4eca67d06ba6 no found"
            },
            {
                "scope": "dictionary",
                "name": "CostCenter",
                "mismatch": null,
                "message": "DomainDefinition for id 3035d8dc-4d9e-9160-6a00-4eca67d06ba6 no found"
            },
            {
                "scope": "dictionary",
                "name": "DashboardComponent",
                "mismatch": null,
                "message": "DomainDefinition for id 3035d8dc-4d9e-9160-6a00-4eca67d06ba6 no found"
            },
            {
                "scope": "dictionary",
                "name": "Dashboard",
                "mismatch": null,
                "message": "DomainDefinition for id 3035d8dc-4d9e-9160-6a00-4eca67d06ba6 no found"
            },
            {
                "scope": "dictionary",
                "name": "sysgdprretentions",
                "mismatch": null,
                "message": "DomainDefinition for id 3035d8dc-4d9e-9160-6a00-4eca67d06ba6 no found"
            },
            {
                "scope": "dictionary",
                "name": "ldap_settings",
                "mismatch": null,
                "message": "DomainDefinition for id 3035d8dc-4d9e-9160-6a00-4eca67d06ba6 no found"
            },
            {
                "scope": "dictionary",
                "name": "PersonalActivity",
                "mismatch": null,
                "message": "DomainDefinition for id 3035d8dc-4d9e-9160-6a00-4eca67d06ba6 no found"
            },
            {
                "scope": "dictionary",
                "name": "spicenotes",
                "mismatch": null,
                "message": "DomainDefinition for id 3035d8dc-4d9e-9160-6a00-4eca67d06ba6 no found"
            },
            {
                "scope": "dictionary",
                "name": "syscategorytreenodes",
                "mismatch": null,
                "message": "DomainDefinition for id 3035d8dc-4d9e-9160-6a00-4eca67d06ba6 no found"
            },
            {
                "scope": "dictionary",
                "name": "Folder",
                "mismatch": null,
                "message": "DomainDefinition for id 3035d8dc-4d9e-9160-6a00-4eca67d06ba6 no found"
            },
            {
                "scope": "dictionary",
                "name": "Letter",
                "mismatch": null,
                "message": "DomainDefinition for id 3035d8dc-4d9e-9160-6a00-4eca67d06ba6 no found"
            },
            {
                "scope": "dictionary",
                "name": "ServiceCalendar",
                "mismatch": null,
                "message": "DomainDefinition for id 3035d8dc-4d9e-9160-6a00-4eca67d06ba6 no found"
            },
            {
                "scope": "dictionary",
                "name": "MediaCategory",
                "mismatch": null,
                "message": "DomainDefinition for id 3035d8dc-4d9e-9160-6a00-4eca67d06ba6 no found"
            },
            {
                "scope": "dictionary",
                "name": "MediaFile",
                "mismatch": null,
                "message": "DomainDefinition for id 3035d8dc-4d9e-9160-6a00-4eca67d06ba6 no found"
            },
            {
                "scope": "dictionary",
                "name": "Meeting",
                "mismatch": null,
                "message": "DomainDefinition for id 3035d8dc-4d9e-9160-6a00-4eca67d06ba6 no found"
            },
            {
                "scope": "dictionary",
                "name": "Note",
                "mismatch": null,
                "message": "DomainDefinition for id 3035d8dc-4d9e-9160-6a00-4eca67d06ba6 no found"
            },
            {
                "scope": "dictionary",
                "name": "OrgChart",
                "mismatch": null,
                "message": "DomainDefinition for id 3035d8dc-4d9e-9160-6a00-4eca67d06ba6 no found"
            },
            {
                "scope": "dictionary",
                "name": "OrgUnit",
                "mismatch": null,
                "message": "DomainDefinition for id 3035d8dc-4d9e-9160-6a00-4eca67d06ba6 no found"
            },
            {
                "scope": "dictionary",
                "name": "OutputTemplate",
                "mismatch": null,
                "message": "DomainDefinition for id 3035d8dc-4d9e-9160-6a00-4eca67d06ba6 no found"
            },
            {
                "scope": "dictionary",
                "name": "ServiceCalendarTime",
                "mismatch": null,
                "message": "DomainDefinition for id 3035d8dc-4d9e-9160-6a00-4eca67d06ba6 no found"
            },
            {
                "scope": "dictionary",
                "name": "Resource",
                "mismatch": null,
                "message": "DomainDefinition for id 3035d8dc-4d9e-9160-6a00-4eca67d06ba6 no found"
            },
            {
                "scope": "dictionary",
                "name": "SchedulerJob",
                "mismatch": null,
                "message": "DomainDefinition for id 3035d8dc-4d9e-9160-6a00-4eca67d06ba6 no found"
            }
        ],
        "line": 299,
        "file": "\/var\/www\/html\/spicecrm-rel2024\/api\/include\/SpiceUI\/SpiceUIConfLoader.php",
        "trace": "#0 \/var\/www\/html\/spicecrm-rel2024\/api\/include\/SpiceUI\/SpiceUIConfLoader.php(214): SpiceCRM\\includes\\SpiceUI\\SpiceUIConfLoader->loadDefaultConf()\n#1 \/var\/www\/html\/spicecrm-rel2024\/api\/modules\/Administration\/api\/controllers\/PackageController.php(104): SpiceCRM\\includes\\SpiceUI\\SpiceUIConfLoader->loadPackage()\n#2 \/var\/www\/html\/spicecrm-rel2024\/api\/vendor\/slim\/slim\/Slim\/Handlers\/Strategies\/RequestResponse.php(38): SpiceCRM\\modules\\Administration\\api\\controllers\\PackageController->loadPackage()\n#3 \/var\/www\/html\/spicecrm-rel2024\/api\/vendor\/slim\/slim\/Slim\/Routing\/Route.php(358): Slim\\Handlers\\Strategies\\RequestResponse->__invoke()\n#4 \/var\/www\/html\/spicecrm-rel2024\/api\/include\/Middleware\/AdminOnlyAccessMiddleware.php(15): Slim\\Routing\\Route->handle()\n#5 \/var\/www\/html\/spicecrm-rel2024\/api\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php(168): SpiceCRM\\includes\\Middleware\\AdminOnlyAccessMiddleware->__invoke()\n#6 \/var\/www\/html\/spicecrm-rel2024\/api\/include\/Middleware\/ValidationMiddleware.php(72): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()\n#7 \/var\/www\/html\/spicecrm-rel2024\/api\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php(168): SpiceCRM\\includes\\Middleware\\ValidationMiddleware->__invoke()\n#8 \/var\/www\/html\/spicecrm-rel2024\/api\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php(65): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()\n#9 \/var\/www\/html\/spicecrm-rel2024\/api\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php(65): Slim\\MiddlewareDispatcher->handle()\n#10 \/var\/www\/html\/spicecrm-rel2024\/api\/vendor\/slim\/slim\/Slim\/Routing\/Route.php(315): Slim\\MiddlewareDispatcher->handle()\n#11 \/var\/www\/html\/spicecrm-rel2024\/api\/vendor\/slim\/slim\/Slim\/Routing\/RouteRunner.php(68): Slim\\Routing\\Route->run()\n#12 \/var\/www\/html\/spicecrm-rel2024\/api\/vendor\/slim\/slim\/Slim\/Middleware\/BodyParsingMiddleware.php(64): Slim\\Routing\\RouteRunner->handle()\n#13 \/var\/www\/html\/spicecrm-rel2024\/api\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php(121): Slim\\Middleware\\BodyParsingMiddleware->process()\n#14 \/var\/www\/html\/spicecrm-rel2024\/api\/include\/Middleware\/DeveloperMiddleware.php(20): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()\n#15 \/var\/www\/html\/spicecrm-rel2024\/api\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php(168): SpiceCRM\\includes\\Middleware\\DeveloperMiddleware->__invoke()\n#16 \/var\/www\/html\/spicecrm-rel2024\/api\/include\/Middleware\/TransactionMiddleware.php(22): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()\n#17 \/var\/www\/html\/spicecrm-rel2024\/api\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php(168): SpiceCRM\\includes\\Middleware\\TransactionMiddleware->__invoke()\n#18 \/var\/www\/html\/spicecrm-rel2024\/api\/include\/RESTManager.php(145): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()\n#19 \/var\/www\/html\/spicecrm-rel2024\/api\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php(269): SpiceCRM\\includes\\RESTManager->SpiceCRM\\includes\\{closure}()\n#20 \/var\/www\/html\/spicecrm-rel2024\/api\/include\/Middleware\/ErrorMiddleware.php(21): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()\n#21 \/var\/www\/html\/spicecrm-rel2024\/api\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php(168): SpiceCRM\\includes\\Middleware\\ErrorMiddleware->__invoke()\n#22 \/var\/www\/html\/spicecrm-rel2024\/api\/include\/Middleware\/ExceptionMiddleware.php(17): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()\n#23 \/var\/www\/html\/spicecrm-rel2024\/api\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php(168): SpiceCRM\\includes\\Middleware\\ExceptionMiddleware->__invoke()\n#24 \/var\/www\/html\/spicecrm-rel2024\/api\/vendor\/slim\/slim\/Slim\/Middleware\/ErrorMiddleware.php(76): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()\n#25 \/var\/www\/html\/spicecrm-rel2024\/api\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php(121): Slim\\Middleware\\ErrorMiddleware->process()\n#26 \/var\/www\/html\/spicecrm-rel2024\/api\/include\/Middleware\/LoggerMiddleware.php(51): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()\n#27 \/var\/www\/html\/spicecrm-rel2024\/api\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php(168): SpiceCRM\\includes\\Middleware\\LoggerMiddleware->__invoke()\n#28 \/var\/www\/html\/spicecrm-rel2024\/api\/vendor\/slim\/slim\/Slim\/Middleware\/RoutingMiddleware.php(45): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()\n#29 \/var\/www\/html\/spicecrm-rel2024\/api\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php(121): Slim\\Middleware\\RoutingMiddleware->process()\n#30 \/var\/www\/html\/spicecrm-rel2024\/api\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php(65): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()\n#31 \/var\/www\/html\/spicecrm-rel2024\/api\/vendor\/slim\/slim\/Slim\/App.php(199): Slim\\MiddlewareDispatcher->handle()\n#32 \/var\/www\/html\/spicecrm-rel2024\/api\/vendor\/slim\/slim\/Slim\/App.php(183): Slim\\App->handle()\n#33 \/var\/www\/html\/spicecrm-rel2024\/api\/index.php(121): Slim\\App->run()\n#34 {main}"
    }
}
```

**Comment by evrim** [comment]
Hi there,

I've managed to fix the error w/ the following type definition in SQL.

```
>
10256a10261
> ('3035d8dc-4d9e-9160-6a00-4eca67d06ba6','bool2','bool','boolean with possible value 0,1 or null','2024.01.001','system','a',0),
10780a10786
> ('404daf2b-780a-43fd-bef8-05a3a6fe9c5e','{sysdictionaryitems.name}',0,'bool','bool2',NULL,0,'3035d8dc-4d9e-9160-6a00-4eca67d06ba6',NULL,0,NULL,'boolean field with possible value 0,1 or null - 2','2024.01.001','system','a',NULL,0),
```

Now all I get is the following:

```
{
    "error": {
        "message": "Failed to load packages core",
        "errorCode": "packageLoadFailed",
        "details": [
            {
                "scope": "dictionary",
                "name": "accounts_contacts",
                "mismatch": null,
                "message": "Key column '' doesn't exist in table last query: \n\r CREATE TABLE accounts_contacts (`id` char(36)  NOT NULL  ,`date_modified` datetime  NULL  ,`deleted` bool  NULL  ,`account_id` char(36)  NULL  ,`contact_id` char(36)  NULL   , KEY idx_accounts_contacts_contid_del_accid (``),   KEY idx_accounts_contacts_alt (``),   UNIQUE accounts_contactspk (``)) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;\n"
            }
        ],
        "line": 299,
        "file": "\/var\/www\/html\/spicecrm-rel2024\/api\/include\/SpiceUI\/SpiceUIConfLoader.php",
        "trace": "#0 \/var\/www\/html\/spicecrm-rel2024\/api\/include\/SpiceUI\/SpiceUIConfLoader.php(214): SpiceCRM\\includes\\SpiceUI\\SpiceUIConfLoader->loadDefaultConf()\n#1 \/var\/www\/html\/spicecrm-rel2024\/api\/modules\/Administration\/api\/controllers\/PackageController.php(104): SpiceCRM\\includes\\SpiceUI\\SpiceUIConfLoader->loadPackage()\n#2 \/var\/www\/html\/spicecrm-rel2024\/api\/vendor\/slim\/slim\/Slim\/Handlers\/Strategies\/RequestResponse.php(38): SpiceCRM\\modules\\Administration\\api\\controllers\\PackageController->loadPackage()\n#3 \/var\/www\/html\/spicecrm-rel2024\/api\/vendor\/slim\/slim\/Slim\/Routing\/Route.php(358): Slim\\Handlers\\Strategies\\RequestResponse->__invoke()\n#4 \/var\/www\/html\/spicecrm-rel2024\/api\/include\/Middleware\/AdminOnlyAccessMiddleware.php(15): Slim\\Routing\\Route->handle()\n#5 \/var\/www\/html\/spicecrm-rel2024\/api\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php(168): SpiceCRM\\includes\\Middleware\\AdminOnlyAccessMiddleware->__invoke()\n#6 \/var\/www\/html\/spicecrm-rel2024\/api\/include\/Middleware\/ValidationMiddleware.php(72): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()\n#7 \/var\/www\/html\/spicecrm-rel2024\/api\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php(168): SpiceCRM\\includes\\Middleware\\ValidationMiddleware->__invoke()\n#8 \/var\/www\/html\/spicecrm-rel2024\/api\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php(65): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()\n#9 \/var\/www\/html\/spicecrm-rel2024\/api\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php(65): Slim\\MiddlewareDispatcher->handle()\n#10 \/var\/www\/html\/spicecrm-rel2024\/api\/vendor\/slim\/slim\/Slim\/Routing\/Route.php(315): Slim\\MiddlewareDispatcher->handle()\n#11 \/var\/www\/html\/spicecrm-rel2024\/api\/vendor\/slim\/slim\/Slim\/Routing\/RouteRunner.php(68): Slim\\Routing\\Route->run()\n#12 \/var\/www\/html\/spicecrm-rel2024\/api\/vendor\/slim\/slim\/Slim\/Middleware\/BodyParsingMiddleware.php(64): Slim\\Routing\\RouteRunner->handle()\n#13 \/var\/www\/html\/spicecrm-rel2024\/api\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php(121): Slim\\Middleware\\BodyParsingMiddleware->process()\n#14 \/var\/www\/html\/spicecrm-rel2024\/api\/include\/Middleware\/DeveloperMiddleware.php(20): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()\n#15 \/var\/www\/html\/spicecrm-rel2024\/api\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php(168): SpiceCRM\\includes\\Middleware\\DeveloperMiddleware->__invoke()\n#16 \/var\/www\/html\/spicecrm-rel2024\/api\/include\/Middleware\/TransactionMiddleware.php(22): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()\n#17 \/var\/www\/html\/spicecrm-rel2024\/api\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php(168): SpiceCRM\\includes\\Middleware\\TransactionMiddleware->__invoke()\n#18 \/var\/www\/html\/spicecrm-rel2024\/api\/include\/RESTManager.php(145): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()\n#19 \/var\/www\/html\/spicecrm-rel2024\/api\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php(269): SpiceCRM\\includes\\RESTManager->SpiceCRM\\includes\\{closure}()\n#20 \/var\/www\/html\/spicecrm-rel2024\/api\/include\/Middleware\/ErrorMiddleware.php(21): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()\n#21 \/var\/www\/html\/spicecrm-rel2024\/api\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php(168): SpiceCRM\\includes\\Middleware\\ErrorMiddleware->__invoke()\n#22 \/var\/www\/html\/spicecrm-rel2024\/api\/include\/Middleware\/ExceptionMiddleware.php(17): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()\n#23 \/var\/www\/html\/spicecrm-rel2024\/api\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php(168): SpiceCRM\\includes\\Middleware\\ExceptionMiddleware->__invoke()\n#24 \/var\/www\/html\/spicecrm-rel2024\/api\/vendor\/slim\/slim\/Slim\/Middleware\/ErrorMiddleware.php(76): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()\n#25 \/var\/www\/html\/spicecrm-rel2024\/api\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php(121): Slim\\Middleware\\ErrorMiddleware->process()\n#26 \/var\/www\/html\/spicecrm-rel2024\/api\/include\/Middleware\/LoggerMiddleware.php(51): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()\n#27 \/var\/www\/html\/spicecrm-rel2024\/api\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php(168): SpiceCRM\\includes\\Middleware\\LoggerMiddleware->__invoke()\n#28 \/var\/www\/html\/spicecrm-rel2024\/api\/vendor\/slim\/slim\/Slim\/Middleware\/RoutingMiddleware.php(45): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()\n#29 \/var\/www\/html\/spicecrm-rel2024\/api\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php(121): Slim\\Middleware\\RoutingMiddleware->process()\n#30 \/var\/www\/html\/spicecrm-rel2024\/api\/vendor\/slim\/slim\/Slim\/MiddlewareDispatcher.php(65): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()\n#31 \/var\/www\/html\/spicecrm-rel2024\/api\/vendor\/slim\/slim\/Slim\/App.php(199): Slim\\MiddlewareDispatcher->handle()\n#32 \/var\/www\/html\/spicecrm-rel2024\/api\/vendor\/slim\/slim\/Slim\/App.php(183): Slim\\App->handle()\n#33 \/var\/www\/html\/spicecrm-rel2024\/api\/index.php(121): Slim\\App->run()\n#34 {main}"
    }
}
```

any ideas?

**Comment by evrim** [comment]
OK, creating the relation table with the following solved the problem.

```

CREATE TABLE accounts_contacts (`id` char(36)  NOT NULL  ,`date_modified` datetime  NULL  ,`deleted` bool  NULL  ,`account_id` char(36)  NULL  ,`contact_id` char(36)  NULL   , KEY idx_accounts_contacts_contid_del_accid (contact_id, dele\
ted, account_id),   KEY idx_accounts_contacts_alt (account_id,contact_id),   UNIQUE accounts_contactspk (id)) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
```

Let me see what's still not working.

**Comment by evrim** [comment]
Here is what I get now:

```
2024-09-18 01:48:44 [116998][1][ERROR][] ["Unable to instantiate bean of unknown module \"History\"."]
2024-09-18 01:48:44 [116998][1][ERROR][] ["Unable to instantiate bean of unknown module \"Activities\"."]
2024-09-18 01:48:44 [116998][1][ERROR][] ["Unable to instantiate bean of unknown module \"Home\"."]
2024-09-18 01:48:44 [116998][1][ERROR][] ["Unable to instantiate bean of unknown module \"Calendar\"."]
2024-09-18 01:48:45 [116998][1][ERROR][] ["Unable to instantiate bean of unknown module \"Application\"."]
2024-09-18 01:48:52 [116979][1][FATAL][SQL] {"error":"Illegal mix of collations for operation 'UNION'","query":"(SELECT package, version FROM syshooks WHERE version is not null AND version <> '') UNION (SELECT package, version FROM sysm\
odules WHERE version is not null AND version <> '') UNION (SELECT package, version FROM sysmodulefilters WHERE version is not null AND version <> '') UNION (SELECT package, version FROM sysuiactionsetitems WHERE version is not null AND \
version <> '') UNION (SELECT package, version FROM sysuiactionsets WHERE version is not null AND version <> '') UNION (SELECT package, version FROM sysuiadmincomponents WHERE version is not null AND version <> '') UNION (SELECT package,\
 version FROM sysuiadmingroups WHERE version is not null AND version <> '') UNION (SELECT package, version FROM sysuicomponentdefaultconf WHERE version is not null AND version <> '') UNION (SELECT package, version FROM sysuicomponentmod\
uleconf WHERE version is not null AND version <> '') UNION (SELECT package, version FROM sysuicomponentsets WHERE version is not null AND version <> '') UNION (SELECT package, version FROM sysuicomponentsetscomponents WHERE version is n\
ot null AND version <> '') UNION (SELECT package, version FROM sysuicopyrules WHERE version is not null AND version <> '') UNION (SELECT package, version FROM sysuidashboarddashlets WHERE version is not null AND version <> '') UNION (SE\
LECT package, version FROM sysuifieldsets WHERE version is not null AND version <> '') UNION (SELECT package, version FROM sysuifieldsetsitems WHERE version is not null AND version <> '') UNION (SELECT package, version FROM sysuifieldty\
pemapping WHERE version is not null AND version <> '') UNION (SELECT package, version FROM sysuilibs WHERE version is not null AND version <> '') UNION (SELECT package, version FROM sysuiloadtaskitems WHERE version is not null AND versi\
on <> '') UNION (SELECT package, version FROM sysuiloadtasks WHERE version is not null AND version <> '') UNION (SELECT package, version FROM sysuifieldtypemapping WHERE version is not null AND version <> '') UNION (SELECT package, vers\
ion FROM sysuimodulerepository WHERE version is not null AND version <> '') UNION (SELECT package, version FROM sysuiobjectrepository WHERE version is not null AND version <> '') UNION (SELECT package, version FROM sysuirolemodules WHER\
E version is not null AND version <> '') UNION (SELECT package, version FROM sysuiroles WHERE version is not null AND version <> '') UNION (SELECT package, version FROM sysuiroutes WHERE version is not null AND version <> '') ORDER BY p\
ackage, version"}
```

Pretty much empty home page without any apps.

**Comment by maretval** [comment]
Package reference for 2024.01.001 is broken. Next version 2024.02.001 shall have functional packages. 
Publication date first half of October 2024

**Comment by evrim** [comment]
Thnx for the answer,

Are there any working old versions that I can install and evaluate before October?

best,
evrim.

**Comment by maretval** [comment]
Evrim.
Please, checkout the branch release_202303001. That should do. 
All the release notes can be found under https://www.spicecrm.com/the-releases/
best,
Val

**Comment by evrim** [comment]
Thanks,

I've tried 202303001 with the following HEAD:

```
commit 7884dde8b2111e667d69bc32caf7c149952b7595 (HEAD -> release_202303001, origin/release_202303001)
Author: maretval <valerie.maret@twentyreasons.com>
Date:   Tue Jan 9 17:10:26 2024 +0100

    packaging

```

Somehow the installation fails with 500 Internal Server Error, the process controller bails out with:

```
json_decode(): Argument #1 ($json) must be of type string, array given
```

Not much debug info given.

Any ideas?

best,
evrim.

**Comment by maretval** [comment]
@evrim Evrim, I had a look at the application and pushed a hotfix.
If you are still up to evaluate the application, you should now be able to install the release_202401001 branch. 

1) Run the installation

2) Run these 2 SQL queries directly in the database
REPLACE INTO `sysdomainfields` (`dbtype`, `fieldtype`, `len`, `required`, `sysdomaindefinition_id`, `sysdomainfieldvalidation_id`, `exclude_from_index`, `defaultvalue`, `description`, `version`, `package`, `status`, `label`, `id`, `name`, `sequence`) VALUES ('bool', 'bool', NULL, 0, '3035d8dc-4d9e-9160-6a00-4eca67d06ba6', '', 0, '0', NULL, '2024.01.001', 'system', 'a', NULL, '16eae52c-61bb-6f79-74a3-8191fd48bcc7', '{sysdictionaryitems.name}', 0);
REPLACE INTO `sysdomaindefinitions` (`id`, `name`, `fieldtype`, `description`, `version`, `package`, `status`) VALUES ('3035d8dc-4d9e-9160-6a00-4eca67d06ba6', 'deleted', 'bool', NULL, '2024.01.001', 'system', 'a');

3) Make sure you are in an incognito browser window before you login

4) Login, workbench > dictionary > repair with execute queries

4) workbench > package > load the core package

5) load additional packages (Opportunity management, Lead management...)

6) workbench > dictionary > repair again with execute queries

That shall do. You will still have some errors on repair but the system shoud be running.

**Comment by evrim** [comment]
Thnx for the comments,

It is still broken as the leads do not appear in the kanban, anyways, Im closing the issue.

best,
evrim.
